name: CI

on:
  push:
    branches: [ testing-action ]
  pull_request:
    branches: [ testing-action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v3

    - name: Run Docker action
      id: custom_action_phpunit
      uses: ./
      with:
        hat-artifact: "examples/test_result_phpunit.xml"
        hat-platform: "phpunit"
        hat-environment: "dev"
        hat-data-type: "xml"

    - run: echo ${{ steps.custom_action_phpunit.outputs.reports }}

    - name: Run Docker action
      id: custom_action_bp
      uses: ./
      with:
        hat-artifact: "examples/test_result_boilerplate.xml"
        hat-platform: "boilerplate"
        hat-environment: "dev"
        hat-data-type: "xml"

    - run: echo ${{ steps.custom_action_bp.outputs.reports }}