name: CI

on:
  push:
    branches: [ testing-action ]
  pull_request:
    branches: [ testing-action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v3

    - name: Run Docker action for phpunit junitxml test results
      id: custom_action_phpunit
      uses: ./
      with:
        hat-artifact: "examples/test_result_phpunit.xml"
        hat-platform: "phpunit"
        hat-environment: "dev"
        hat-data-type: "xml"

    - name: Print phpunit gha result
      run: echo ${{ steps.custom_action_phpunit.outputs.reports }}

    - name: Run Docker action for boilerplate junitxml test results file
      id: custom_action_bp
      uses: ./
      with:
        hat-artifact: "examples/test_result_boilerplate.xml"
        hat-platform: "boilerplate"
        hat-environment: "dev"
        hat-data-type: "xml"

    - name: Print boilerplate gha result
      run: echo ${{ steps.custom_action_bp.outputs.reports }}

    - name: Read json file to variable
      id: encode_json
      run: echo "::set-output name=data::$(base64 -w 0 < examples/test_data_boilerplate.json)"
      shell: bash

    - name: Run Docker action for boilerplate json test results bas64 encoded
      id: custom_action_bp_json
      uses: ./
      with:
        hat-artifact: "examples/test_result_boilerplate.json"
        hat-platform: "boilerplate"
        hat-environment: "dev"
        hat-data-type: "json"

    - name: Print boilerplate gha result
      run: echo ${{ steps.custom_action_bp.outputs.reports }}
